http {
    server {
        listen 80;
        
        server_name _;

        return 301 https://$host$uri$is_args$args;

    }

    server {
        listen  443;

        server_name _;

        proxy_ssl_verify off;

        location / {
            set $upstream https://web/;

            proxy_pass https://$upstream$uri$is_args$args;
        }

        location /api/ {
            set $upstream https://api/api/;

            proxy_pass http://
        }
    }
}
