events {}

http {
    resolver 127.0.0.11 ipv6=off;

    server {
        listen 80;
        
        location / {
            set $upstream http://web/;

            proxy_pass $upstream$uri$is_args$args;
        }

        location /api/ {
            set $upstream http://api/api/;

            proxy_pass $upstream$uri$is_args$args;
        }

    }

    server {
        listen  443;

        return 301 http://$host$uri$is_args$args;
        
    }
}
