events {}

http {
    index main.html;
    root /app/;

    server {
        listen  80;
        location / {
            
        }
    }

    server {
        listen 443;
        location / {
            return 301 http://$host$request_uri;
        }
    }
}
